SELECT *
FROM customer;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,
       purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >=
    (SELECT AVG(purchase_amount)
     FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 item_purchased,
           ROUND(AVG(review_rating), 4) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type,
       ROUND(AVG(purchase_amount), 4) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard',
                        'Express')
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS average_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5 item_purchased,
           (SUM(CASE
                    WHEN discount_applied = 'Yes' THEN 1.0
                    ELSE 0.0
                END) / COUNT(*)) * 100 AS discount_dependency_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_dependency_percentage DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH CustomerSegments AS
  (SELECT customer_id,
          CASE
              WHEN previous_purchases = 1 THEN 'New'
              WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
              ELSE 'Loyal'
          END AS SEGMENT
   FROM customer)
SELECT SEGMENT,
       COUNT(customer_id) AS total_customer
FROM CustomerSegments
GROUP BY SEGMENT
ORDER BY total_customer DESC;

--Q8. What are the top 3 most purchased products within each category?
WITH ProductSales AS
  (SELECT category,
          item_purchased,
          COUNT(*) AS total_orders
   FROM customer
   GROUP BY category,
            item_purchased),
     RankedProducts AS
  (SELECT category,
          item_purchased,
          total_orders,
          DENSE_RANK() OVER(PARTITION BY category
                            ORDER BY total_orders DESC) AS rank_num
   FROM ProductSales)
SELECT category,
       item_purchased,
       total_orders,
       rank_num
FROM RankedProducts
WHERE rank_num <=3
ORDER BY category ASC,
         rank_num ASC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       count(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?

SELECT age_group,
       sum(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;